package entities;
// Generated Jun 7, 2017 3:32:32 PM by Hibernate Tools 4.3.1



/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung  implements java.io.Serializable {


     private Integer idNguoiDung;
     private String hoTen;
     private String tendangnhap;
     private String matkhau;
     private int phanquyen;

    public Nguoidung() {
    }

    public Nguoidung(String hoTen, String tendangnhap, String matkhau, int phanquyen) {
       this.hoTen = hoTen;
       this.tendangnhap = tendangnhap;
       this.matkhau = matkhau;
       this.phanquyen = phanquyen;
    }
   
    public Integer getIdNguoiDung() {
        return this.idNguoiDung;
    }
    
    public void setIdNguoiDung(Integer idNguoiDung) {
        this.idNguoiDung = idNguoiDung;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getTendangnhap() {
        return this.tendangnhap;
    }
    
    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public int getPhanquyen() {
        return this.phanquyen;
    }
    
    public void setPhanquyen(int phanquyen) {
        this.phanquyen = phanquyen;
    }




}


