package entities;
// Generated Jun 7, 2017 3:32:32 PM by Hibernate Tools 4.3.1



/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private Integer idSanPham;
     private String tenSanPham;
     private int giaSanPham;

    public Sanpham() {
    }

    public Sanpham(String tenSanPham, int giaSanPham) {
       this.tenSanPham = tenSanPham;
       this.giaSanPham = giaSanPham;
    }
   
    public Integer getIdSanPham() {
        return this.idSanPham;
    }
    
    public void setIdSanPham(Integer idSanPham) {
        this.idSanPham = idSanPham;
    }
    public String getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public int getGiaSanPham() {
        return this.giaSanPham;
    }
    
    public void setGiaSanPham(int giaSanPham) {
        this.giaSanPham = giaSanPham;
    }




}


